name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build the Docker image
        id: build
        run: docker build . --file Dockerfile --tag jayabs/pi-bt-radio:latest

  push:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Push Docker image to Docker Hub
        run: |
          TIMESTAMP=$(date +%s)
          docker tag jayabs/pi-bt-radio:latest jayabs/pi-bt-radio:$TIMESTAMP
          docker push jayabs/pi-bt-radio:latest
          docker push jayabs/pi-bt-radio:$TIMESTAMP
          
