# Author - JB
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pi-bt-radio:${{ github.sha }} .

      - name: Verify Docker image build
        run: docker images 

  build-and-push:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pi-bt-radio:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify Docker image presence before tagging
        run: |
          docker images
          docker tag ${{ secrets.DOCKER_USERNAME }}/pi-bt-radio:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/pi-bt-radio:latest
          
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pi-bt-radio:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/pi-bt-radio:latest
          
