name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build the Docker image
        run: |
          TIMESTAMP=$(date +%s)
          docker build . --file Dockerfile --tag jayabs/pi-bt-radio:$TIMESTAMP

  push:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: echo "DOCKERHUB_USERNAME: ${ { secrets.DOCKERHUB_USERNAME } }"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Push Docker image to Docker Hub
        run: |
          docker tag jayabs/pi-bt-radio:$TIMESTAMP jayabs/pi-bt-radio:latest
          docker push jayabs/pi-bt-radio:latest
          docker push jayabs/pi-bt-radio:$TIMESTAMP
          
